AWS_ACCESS_KEY = "aws_access_key"
AWS_SECRET_KEY = "aws_secret_key"
AWS_REGION	   = "us-west-1"
PATH_TO_PUBLIC_KEY = "/home/ubuntu/.ssh/mykey.pub"
PATH_TO_PRIVATE_KEY = "/home/ubuntu/.ssh/mykey.ppk"
INSTANCE_USERNAME = "ubuntu"
#PATH_TO_PUBLIC_KEY = "/home/ubuntu/.ssh/id_rsa.pub"
#PATH_TO_PRIVATE_KEY = "/home/ubuntu/.ssh/id_rsa"
